// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxoyctqlhqhkfrhzmtbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4b3ljdHFsaHFoa2ZyaHptdGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTA3OTUsImV4cCI6MjA1OTI4Njc5NX0.iE4f0BFfPJMqfE8KU4qbQZdz20aQ8ynG9Z0fS794PsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);